In [1]:
import numpy as np

## 1.	Explain the difference between deep copy and shallow copy in NumPy arrays.

### Deep Copy
Definition: A deep copy creates a new object and recursively copies all objects found in the original. It duplicates everything, including nested objects.
### Shallow Copy
Definition: A shallow copy creates a new object, but inserts references into it to the objects found in the original. It copies the outer structure but not the nested objects.

## 2. Explain the difference between array and list?

### list
* a list contain different types of data types.
* list have huge memory usage
### array
* array contain same data type
* less memory usage
* stored in contigenously location
* item wise computetion is possible

## 3.	Given an array a = np.array([10, 20, 30]), how do you square every element in the array?

In [6]:
arr = np.array([10, 20, 30])
arr

array([10, 20, 30])

In [10]:
sq = np.square(arr)
sq

array([100, 400, 900])

## 4.	How do you create an array of zeros with shape (3, 4)?

In [20]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 5.	Given the 1D array a = np.array([1, 2, 3, 4, 5]), how do you calculate the cumulative sum of the elements?

In [23]:
cm = np.array([1, 2, 3, 4, 5])
cm

array([1, 2, 3, 4, 5])

In [42]:
arr = cm.cumsum()
arr

array([ 1,  3,  6, 10, 15])

## 6.	How do you reverse the elements in a NumPy array a = np.array([1, 2, 3, 4, 5])?

In [34]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [51]:
array[::-1]

array([5, 4, 3, 2, 1])

## 7.	How do you find the indices of elements that are greater than 4 in the array a = np.array([1, 2, 3, 4, 5, 6, 7])?


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
for idx,x in np.ndenumerate(arr):
   if x>4:
       print(idx,x)
      

(4,) 5
(5,) 6
(6,) 7


## 8.	How do you create a 2D array with random floating-point numbers between 0 and 1 of shape (3, 3)?

In [97]:
arr = np.random.rand(3,3)
arr

array([[0.67457996, 0.79399947, 0.38741513],
       [0.2930919 , 0.37908106, 0.98877965],
       [0.70739244, 0.26795969, 0.49276949]])

## 9.	Extract the elements at indices [0, 2, 4] from the array a = np.array([10, 20, 30, 40, 50]).

In [100]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [108]:
a[0::2]

array([10, 30, 50])

## 10.	Given the array a = np.array([10, 20, 30, 40]), how do you normalize the array so that its values are between 0 and 1?

In [120]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [122]:
b = (a-np.min(a))/(np.max(a)-np.min(a))
b

array([0.        , 0.33333333, 0.66666667, 1.        ])

## 11.	How do you concatenate two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) along the first axis?

In [128]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 

In [132]:
arr = np.concatenate((a,b),axis = 0)
arr

array([1, 2, 3, 4, 5, 6])

## 12.	How do you find the dot product of two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])?

In [135]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [143]:
arr = np.dot(a,b)
arr

32

## 13.	How do you create an identity matrix of size 4x4?

In [150]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 14.	How do you generate an array with random integers between 1 and 100, of shape (4, 4)?

In [159]:
arr = np.random.randint(1,100,size = (4,4))
arr

array([[83, 61, 14, 30],
       [32, 14, 24, 26],
       [98, 27, 18, 10],
       [ 1, 13, 35, 25]])

## 15.	How do you split a NumPy array a = np.array([1, 2, 3, 4, 5, 6]) into three sub-arrays?

In [162]:
a = np.array([1, 2, 3, 4, 5, 6]) 

In [168]:
split = np.split(a,3)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

## 16.	Given the 2D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how do you compute the sum of all elements along the second axis?

In [171]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [175]:
sum = a.sum(axis = 1)
sum

array([ 6, 15, 24])

## 17.	How do you compute the element-wise maximum of two arrays a = np.array([1, 2, 3]) and b = np.array([3, 2, 1])?

In [178]:
a = np.array([1, 2, 3]) 
b = np.array([3, 2, 1])

In [188]:
arr = np.maximum(a,b)
arr

array([3, 2, 3])

## 18.	How do you find the unique elements in the array a = np.array([1, 2, 2, 3, 3, 4, 5])?

In [191]:
a = np.array([1, 2, 2, 3, 3, 4, 5])

In [206]:
arr = np.unique(a)
arr

array([1, 2, 3, 4, 5])

## 19.	How do you use np.arange to create an array of values between 1 and 50 with a step of 3, and then filter the elements that are divisible by 5?

In [263]:
arr = np.arange(1,50,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [267]:
filter = arr%5==0
filter= arr[filter]
filter

array([10, 25, 40])

## 20.	Given the array a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), use np.where to replace elements in a that are less than 3 with -3, then  horizontally stack a and b.

In [253]:
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([6, 7, 8, 9, 10])

In [273]:
rep = np.where(a<3,-3,a)
d = np.hstack((rep,b))
d

array([-3, -3,  3,  4,  5,  6,  7,  8,  9, 10])

## 21.	How do you generate a 3D array of shape (4, 3, 2) where each 2D slice (3x2) is filled with random values between 0 and 1, and then normalize the entire 3D array to values between 0 and 1 (with respect to the min and max of the array)?

In [289]:
np.random.seed(42)
arr = np.random.rand(4,3,2)
arr

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848],
        [0.15601864, 0.15599452]],

       [[0.05808361, 0.86617615],
        [0.60111501, 0.70807258],
        [0.02058449, 0.96990985]],

       [[0.83244264, 0.21233911],
        [0.18182497, 0.18340451],
        [0.30424224, 0.52475643]],

       [[0.43194502, 0.29122914],
        [0.61185289, 0.13949386],
        [0.29214465, 0.36636184]]])

In [291]:
nor = (arr-np.min(arr))/(np.max(arr)-np.min(arr))
nor

array([[[0.37284965, 0.9797798 ],
        [0.74938422, 0.60893137],
        [0.14266357, 0.14263816]],

       [[0.03950081, 0.89072903],
        [0.61151903, 0.72418595],
        [0.        , 1.        ]],

       [[0.85519484, 0.20199041],
        [0.16984743, 0.17151129],
        [0.2987993 , 0.53108445]],

       [[0.4333188 , 0.28509156],
        [0.62283009, 0.12525671],
        [0.28605594, 0.36423482]]])

## 22.	Given a 2D array of shape (5, 5) filled with random integers between 1 and 100, replace all odd numbers with -1 and all even numbers with 1.

In [294]:
arr = np.random.randint(1,100,size=(5,5))
arr

array([[62, 62, 47, 62, 51],
       [55, 64,  3, 51,  7],
       [21, 73, 39, 18,  4],
       [89, 60, 14,  9, 90],
       [53,  2, 84, 92, 60]])

In [312]:
rep = np.where(arr%2==0,1,-1)
rep

array([[ 1,  1, -1,  1, -1],
       [-1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1],
       [-1,  1,  1, -1,  1],
       [-1,  1,  1,  1,  1]])

## 23.	Given a large 1D array of 10 million random floating-point numbers between 0 and 1, find the 10th and 90th percentile of the values.## 

In [315]:
arr =np.random.rand(10000000)
arr

array([0.12203823, 0.49517691, 0.03438852, ..., 0.81595227, 0.63648839,
       0.08875056])

In [317]:
per = np.percentile(arr,10)
perc = np.percentile(arr,90)
print(per)
print(perc)

0.0998946347916304
0.8998586403668534


## 24.	Given a 5x5 matrix arr, use np.where to:
•	Replace all elements greater than 10 with the value 100.

•	Replace all elements less than or equal to 10 with the value -100


In [327]:
arr = np.arange(0,25)
res = arr.reshape(5,5)

In [331]:
a = np.where(res>10,100,-100)
a

array([[-100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100],
       [-100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100]])

## 25.	Given a 2D array arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), perform the following operations:
•	Horizontally split the array into two equal parts.
•	Vertically split the array into three equal parts.
•	Stack the split parts vertically and horizontally.


In [334]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [375]:
splth = np.array_split(arr,2,axis = 1)
splth

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [359]:
spltv = np.array_split(arr,3)
spltv

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]