In [2]:
import numpy as np

In [3]:
a = [1,2,3]

In [4]:
b = [4,5,6]

In [5]:
da = a+b

In [6]:
da

[1, 2, 3, 4, 5, 6]

Introduction to NumPy

•	NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays

What is an Array in Python?

•	An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together.

Q) Why Use NumPy?

 •	In Python we have lists that serve the purpose of arrays, but they are slow to process.

 •	NumPy aims to provide an array object that is up to 50x faster than traditional Python  lists.

 •	The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

 •	Arrays are very frequently used in data science, where speed and resources are very important.

Q) Why is NumPy Faster Than Lists?

 •	NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

 •	This behaviour is called locality of reference in computer science.

 •	This is the main reason why NumPy is faster than lists. Also, it is optimized to work with latest CPU architectures.

 •	No need for data type checking.

 •	Item wise

computations available.

# Create Numpy ndarray Object

### 0 Dimensional array

In [11]:
arr = np.array(34)
arr

array(34)

### 1 Dimensional array
An array that has  0-D arrays as its elements its called uni-dimensional or 1-D array

In [13]:
oned = np.array([1,2,3])
oned

array([1, 2, 3])

### 2 dimensional
An array that has 1-D arrays as its elements its called uni-dimensional or 2-D array

In [15]:
twod = np.array([
    [1,2,3],
    [4,5,6]
                ])
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
four = np.array([
    [1,2,3,5],
    [4,5,6,6],
    [7,8,9,5],
    [1,0,2,5]])
four

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 5],
       [1, 0, 2, 5]])

In [17]:
Three = np.array([[1,2,3,],
                 [4,5,6,],
                 [7,8,9],
                 [10,11,12]])
Three

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
type(Three)

numpy.ndarray

### 3 Dimensional
An array that has 2-D arrays as its elements its called uni-dimensional or 3-D array

In [20]:
threed = np.array([
    [[1,2,3],[1,2,3,]],
    [[1,2,3],[1,2,3]]
                   ])
threed

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [21]:
thred = np.array([
    [[1,2,3],[1,2,3],[1,2,3]],
    [[4,5,6],[4,5,6],[4,5,6]],
    [[7,8,9],[7,8,9],[7,8,9]]
])
thred

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]]])

### checking Dimension

In [23]:
thred.ndim

3

In [24]:
thred.size

27

In [25]:
thred.shape

(3, 3, 3)

In [26]:
thred.dtype

dtype('int32')

In [27]:
a = np.array([
    [[1,2,3,4,5],
    [6,7,8,9,10]],
    
    [[1,2,3,4,5],
    [6,7,8,9,10]],
    
    [[1,2,3,4,5],
    [6,7,8,9,10]]])
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [28]:
a.ndim

3

In [29]:
a.shape

(3, 2, 5)

In [30]:
a.size

30

In [31]:
a[2,1,2]

8

### 4 Dimensional
An array that has 3-D arrays as its elements its called uni-dimensional or 4-D array

In [33]:
fourd = np.array([[[
    [1,2,3],[1,2,3,]],
    [[1,2,3],[1,2,3]]
                   ]])

In [34]:
fourd

array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]])

In [35]:
four_two_thre = np.array([[
    [1,2,3],[1,2,3]],
                          
    [[1,2,3],[1,2,3]],
                          
    [[4,5,6,],[4,5,6]],
                          
    [[7,8,9],[7,8,9]
]])

In [36]:
four_two_thre

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9]]])

In [37]:
four_two_thre.shape

(4, 2, 3)

In [38]:
four_two_thre[2,0,2]

6

In [39]:
df= np.array([[
    [1,2,3,4],
    [3,4,5,6]],
    [[11,12,13,14],
    [15,16,17,18]
]])

In [40]:
#accessing element 5
df[0,1,2]

5

## Negative Slicing

In [42]:
arr1 = np.array([1,2,3,4])

In [43]:
arr1[-1]

4

In [44]:
arr2=np.array([[1,2,3],[4,5,6]])

In [45]:
arr2[-1,-1]

6

In [46]:
arr2[1,-2]

5

In [47]:
df = np.array([[1,2,3,4],[5,6,7,8]])

In [48]:
df.shape

(2, 4)

In [49]:
df[-1,-2]

7

## Slicing arrays

In [51]:
df = np.array([[1,2,3,4],[5,6,7,8]])

In [52]:
df[0,1:]

array([2, 3, 4])

In [53]:
df[0,:2]

array([1, 2])

In [54]:
arr2 = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18]])

In [55]:
arr2[:,2:5]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [56]:
arr2.shape

(3, 6)

In [57]:
arr3 = np.array([[
    [1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]],
    [[25,26,27,28,29,30],[31,32,33,34,35,36],[37,38,39,40,41,42],[43,44,45,46,47,48]             
]])

In [58]:
arr3.shape

(2, 4, 6)

In [59]:
arr3[0,:,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [60]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [61]:
arr[2::5]

array([3, 8])

In [62]:
arr[::4]

array([1, 5, 9])

In [63]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [64]:
arr2[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [65]:
thsix=np.array([[1,2,3,4,5,6],
          [7,8,9,10,11,12],
          [13,14,15,16,17,18]])

In [66]:
thsix[:,2::3]

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [67]:
thsix[:,::3]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [68]:
fouthr = np.array([
    [1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]
                  ])

In [69]:
fouthr.shape

(4, 6)

In [70]:
fouthr[1:,::3]

array([[ 7, 10],
       [13, 16],
       [19, 22]])

## data types convret

In [72]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [73]:
arr = np.array([1,2,3,4],dtype = 'S')
print(arr.dtype)
arr

|S1


array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [74]:
arr = np.array([1,2,3,4],dtype = 'f')
print(arr.dtype)
arr

float32


array([1., 2., 3., 4.], dtype=float32)

In [75]:
arr = np.array([1.1,2.1,3.1,4.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [76]:
arrs = newarr.astype('S')
print(arrs)
print(arrs.dtype)

[b'1' b'2' b'3' b'4']
|S11


## copy and view

### Copy

In [79]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [80]:
arr[0]  = 42

In [81]:
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [82]:
arr1 = np.array([10,11,12,13,14,15])
arr1

array([10, 11, 12, 13, 14, 15])

In [83]:
arr1[1] = 32
arr1

array([10, 32, 12, 13, 14, 15])

In [84]:
y = arr1.copy()
y

array([10, 32, 12, 13, 14, 15])

In [85]:
print(arr1)
print(y)

[10 32 12 13 14 15]
[10 32 12 13 14 15]


### View

In [87]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [88]:
n = arr.view()
n

array([4, 5, 6, 7, 8])

In [89]:
arr[0] = 32
arr

array([32,  5,  6,  7,  8])

In [90]:
print(arr)
print(n)

[32  5  6  7  8]
[32  5  6  7  8]


In [91]:
arr2 = np.array([2,4,6,8])
arr2

array([2, 4, 6, 8])

In [92]:
s = arr2.view()
s

array([2, 4, 6, 8])

In [93]:
s[0] = 42
s

array([42,  4,  6,  8])

In [94]:
print(arr2)
print(s)

[42  4  6  8]
[42  4  6  8]


## check copy or view
### base()

In [96]:
arr4 = np.array([1,3,5,7,9])

In [97]:
y = arr4.view()
x = arr4.copy()

In [98]:
print(y.base)

[1 3 5 7 9]


In [99]:
print(x.base)

None


In [100]:
arr5 = np.array([[1,2],[4,5],[7,8]])

In [101]:
arr5.shape

(3, 2)

## diomeansion convert

In [103]:
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [104]:
print(arr6.shape)
print(arr6.ndim)

(4, 4)
2


In [105]:
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],ndmin = 4)

In [106]:
arr6

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [107]:
arr = np.array([
    [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]
]])

In [108]:
arr.shape

(2, 3, 5)

In [109]:
arr.size

30

In [110]:
arr.ndim

3

## Reshaping Arrays

In [112]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [113]:
newarr = arr1.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [114]:
newarr3 = arr1.reshape(2,3,2)
newarr3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [115]:
newarr4 = arr1.reshape(1,2,2,3)
newarr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [116]:
arr = np.array([
    [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]
]])

In [117]:
newarr = arr.reshape(6,5)
newarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [118]:
newarr4 = arr.reshape(3,1,2,5)
newarr4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]],


       [[[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]]])

In [119]:
print(newarr4.base)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [120]:
arr1 = np.array([1,2,3,4],ndmin = 6)
arr1

array([[[[[[1, 2, 3, 4]]]]]])

## Diomantion create funtion

### 1.Arange()

In [122]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
numerr = arr.reshape(5,2)
numerr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [124]:
arr1 = np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [125]:
arr3 = np.arange(0,12,3)
arr3

array([0, 3, 6, 9])

### 2. ones()

In [127]:
arr = np.ones((3,4),dtype = 'i')
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [128]:
arr3 = np.ones((2,2,3),dtype = 'i')
arr3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

### 3. Zeros()

In [130]:
arr = np.zeros((3,2),dtype = 'i')
arr

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [131]:
arr = np.zeros((2,2,3),dtype = 'i')
arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [132]:
arr1 = np.zeros(5,dtype = 'i')
arr1

array([0, 0, 0, 0, 0], dtype=int32)

### 4. linspace()

In [134]:
arr = np.linspace(1,50,5)
arr

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [135]:
arr =np.linspace(0,50,5)
arr

array([ 0. , 12.5, 25. , 37.5, 50. ])

### 5. diag()

In [137]:
f = np.diag([3,4,5,6,7,8])
f

array([[3, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 8]])

In [138]:
c = np.diag([3])
c

array([[3]])

### 6. eye()

In [140]:
arr = np.eye((3),dtype = 'i')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [141]:
ara = np.arange(20,35)
ara

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [142]:
x = ara.reshape(5,3)
x

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]])

In [143]:
ar0 = np.arange(0,15)
ar0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## mathmatical operators
### 1. Add()

In [145]:
add = np.add(ara,ar0)

In [146]:
add

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

### 2. subtract()

In [148]:
sub = np.subtract(ara,ar0)

In [149]:
sub

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

### 3. multiply()

In [151]:
mul = np.multiply(ara,ar0)

In [152]:
mul

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476])

### 4. dot()

In [154]:
dot = np.dot(ar0,ara)

In [155]:
dot

3115

### 5. sum()

In [157]:
sum = np.sum(ar0)
sum

105

### 6. mea()

In [159]:
mean = np.mean(ar0)

In [160]:
mean

7.0

### 7. standerd deviation()

In [162]:
std = np.std(ar0)

In [163]:
std

4.320493798938574

### 8. variance()

In [165]:
var = np.var(ar0)

In [166]:
var

18.666666666666668

### 9. max()

In [168]:
max = np.max(ar0)

In [169]:
max

14

### 10.min()

In [171]:
min = np.min(ar0)

In [172]:
min

0

In [173]:
arr = np.linspace(0,40,8)

In [174]:
arr

array([ 0.        ,  5.71428571, 11.42857143, 17.14285714, 22.85714286,
       28.57142857, 34.28571429, 40.        ])

In [175]:
x = arr.reshape(2,4)

In [176]:
x

array([[ 0.        ,  5.71428571, 11.42857143, 17.14285714],
       [22.85714286, 28.57142857, 34.28571429, 40.        ]])

## flattening the arrays

In [178]:
newarr = x.reshape(-1)

In [179]:
newarr

array([ 0.        ,  5.71428571, 11.42857143, 17.14285714, 22.85714286,
       28.57142857, 34.28571429, 40.        ])

In [180]:
max = np.max(newarr)

In [181]:
max

40.0

In [182]:
min = np.min(newarr)

In [183]:
min

0.0

In [184]:
mean = np.mean(newarr)

In [185]:
mean

20.0

In [186]:
std = np.std(newarr)

In [187]:
std

13.093073414159543

In [188]:
sum = np.sum(newarr)

In [189]:
sum

160.0

In [190]:
var = np.var(newarr)

In [191]:
var

171.42857142857144

In [192]:
arr1 = np.arange(0,18)

In [193]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [194]:
res = arr1.reshape(1,3,6)

In [195]:
res

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]])

In [196]:
res1 = arr1.reshape(-2)

In [197]:
res1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [198]:
mean = np.mean(res1)

In [199]:
mean

8.5

In [200]:
sum = np.sum(res1)
sum

153

In [201]:
std = np.sum(res1)
std

153

In [202]:
max = np.max(res1)
max

17

In [203]:
min = np.min(res1)
min

0

In [204]:
var = np.var(res1)
var

26.916666666666668

### print iter

In [206]:
for i in res1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [207]:
res2 = res1.reshape(3,6)

In [208]:
res2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [209]:
for i in res2:
    for j in i:
        print(j)
   

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [210]:
res

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]])

In [211]:
for i in res:
    for two in i:
        for one in two:
            print(one)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## Iterating Arrays Using (nditer)

In [213]:
for x in np.nditer(res):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [214]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [215]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6


# Enumerated Iteration Using ndenumerate()

* ## Enumeration means mentioning sequence number of somethings one by one.
* ## Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those use cases.

In [217]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [218]:
for idx,x in np.ndenumerate(arr2):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [219]:
for idx,x in np.ndenumerate(res):
    print(idx,x)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 0, 3) 3
(0, 0, 4) 4
(0, 0, 5) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 1, 5) 11
(0, 2, 0) 12
(0, 2, 1) 13
(0, 2, 2) 14
(0, 2, 3) 15
(0, 2, 4) 16
(0, 2, 5) 17


## Joining Numpy Arrays

In [221]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [222]:
arr = np.concatenate((arr1,arr2))

In [223]:
arr

array([1, 2, 3, 4, 5, 6])

In [224]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[10,12,13]])

In [225]:
arrr = np.concatenate((arr1,arr2),axis = 1)

Column Wise Change

In [227]:
arrr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 12, 13]])

In [228]:
arrr = np.concatenate((arr1,arr2))

Row wise Change

In [230]:
arrr

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 12, 13]])

In [231]:
arr = np.arange(0,24)

In [232]:
arr1 = arr.reshape(2,2,6)
arr2 = arr.reshape(2,2,6)

In [233]:
arr2

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [234]:
arr1

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [235]:
arrc = np.concatenate((arr1,arr2))

In [236]:
arrc

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [237]:
arrc = np.concatenate((arr1,arr2),axis = 1)

In [238]:
arrc

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

## Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

Unlike the concatenate() function, the stack() function joins 1D arrays to be one 2D array and joins 2D arrays to be one 3D array.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.
### CHOOSING BETWEEN STACK AND CONCATENATION:

The choice depends on your desired outcome:

If you want to combine arrays with a new level of organization, use stack.

If you simply want to join arrays along an existing dimension, use concatenate.

In [240]:
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])

In [241]:
arr = np.stack((arr1,arr2))

In [242]:
arr

array([[1, 2, 3],
       [7, 8, 9]])

In [243]:
arr = np.stack((arr1,arr2),axis = 1)

In [244]:
arr

array([[1, 7],
       [2, 8],
       [3, 9]])

In [245]:
arr = np.concatenate((arr1,arr2))

In [246]:
arr

array([1, 2, 3, 7, 8, 9])

### horizontal

In [248]:
arrh = np.hstack((arr1,arr2))

In [249]:
arrh

array([1, 2, 3, 7, 8, 9])

In [250]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [251]:
arrh = np.hstack((arr1,arr2))

In [252]:
arrh

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [253]:
arr = np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18],[19,20,21],[22,23,24]],
    [[25,26,27],[28,29,30],[31,32,33],[34,35,36]]
])

In [254]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [255]:
arr.shape

(3, 4, 3)

In [256]:
arr[1,:,:]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [257]:
arr[1,::2,:]

array([[13, 14, 15],
       [19, 20, 21]])

In [258]:
arr[1,::2,::2]

array([[13, 15],
       [19, 21]])

In [259]:
arr[:,2::,:]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [260]:
arr[1,:,1::2]

array([[14],
       [17],
       [20],
       [23]])

In [261]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [262]:
arr2 = np.array([[1,2,3],[4,5,6]],ndmin = 6)

In [263]:
arr2

array([[[[[[1, 2, 3],
           [4, 5, 6]]]]]])

In [264]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6


In [265]:
for x in np.ndenumerate(arr2):
    print(x)

((0, 0, 0, 0, 0, 0), 1)
((0, 0, 0, 0, 0, 1), 2)
((0, 0, 0, 0, 0, 2), 3)
((0, 0, 0, 0, 1, 0), 4)
((0, 0, 0, 0, 1, 1), 5)
((0, 0, 0, 0, 1, 2), 6)


In [266]:
arr = np.array([[1,2,3],[4,5,6]])

In [267]:
for x in np.ndenumerate(arr):
    print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


In [268]:
sum = np.sum(arr2)

In [269]:
sum

21

In [270]:
min = np.min(arr2)
min

1

In [271]:
max = np.max(arr2)

In [272]:
max

6

In [273]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [274]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [275]:
arrh = np.hstack((arr1,arr2))
arrh

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [276]:
arrh = np.stack((arr1,arr2),axis = 1)
arrh

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [277]:
arrrh = np.concatenate((arr1,arr2),axis = 1)
arrrh

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## vstack

In [279]:
arrh = np.vstack((arr1,arr2))
arrh

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Array_split
•	Splitting is reverse operation of Joining.

•	Joining merges multiple arrays into one and Splitting breaks one array into multiple.

•	We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

•	If the array has less elements than required, it will adjust from the end accordingly.

In [281]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [282]:
newarr = np.array_split(arr,2)
newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [283]:
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [284]:
newarr = np.array_split(arr,5)
newarr

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [285]:
newarr = np.split(arr,2)
newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [286]:
newarr = np.split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

We also have the method split() available but it will ### not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [288]:
newarr = np.split(arr,5)
newarr

ValueError: array split does not result in an equal division

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

In [ ]:
newarr = np.array_split(arr,3)
newarr

In [ ]:
arr = np.array([
    [1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

In [ ]:
newarr = np.array_split(arr,2)
newarr

In [ ]:
newarr = np.array_split(arr,2,axis = 1)
newarr

## Searching Arrays
•	You can search an array for a certain value, and return the indexes that get a match.

•	To search an array, use the where() method.

•	For replacing a value in a array using where()

•	np.where(condition, x, y)

•	condition: An array-like structure that contains boolean values (True or False).

•	x: The values to place in the output array where the condition is True.

•	y: The values to place in the output array where the condition is False.

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr

In [ ]:
newarr = np.where(arr == 2)
newarr

In [ ]:
newarr = np.where(arr == 5)
newarr

In [ ]:
arr = np.array([1,2,3,4,5,6,1,2,3,4,5,6])
arr

In [ ]:
newarr = np.where(arr == 5)
newarr

In [ ]:
arr = np.array([1,2,3,4,5,6,1,2,3,4,5,6])
arr

In [ ]:
oddnum = np.where(arr%2== 1)
oddnum

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,12,11,13,14])
arr

In [ ]:
a = np.where(arr<5,0,arr)
a

In [ ]:
arr = np.arange(1,13)

In [ ]:
arr2 = arr.reshape(3,4)
arr2

In [ ]:
a = np.where(arr2==5)
a

In [ ]:
a = np.where(arr2%3==0,arr2+1,arr2)
a

In [ ]:
a = np.where(arr2<3,arr2*-1,arr2)
a

## Sort Arrays
• Sorting means putting elements in an ordered sequence.

• Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

• The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [ ]:
arr = np.array([1,5,9,2,3,0])


In [ ]:
x = np.sort(arr)
x

In [ ]:
x = np.sort(arr)[::-1]
x

In [ ]:
arr = np.arange(1,13)
arr

In [ ]:
x = np.sort(arr)[::-1]
x

In [ ]:
arr2 = arr.reshape(3,4)
print(np.sort(arr2))

In [ ]:
arr2

In [ ]:
x = np.sort(arr2)[::-1]

In [ ]:
x

In [ ]:
x = np.sort(arr2)[::-1,::-1]

In [ ]:
x

## Search Sorted (Optional)

•	There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

•	The searchsorted() method is assumed to be used on sorted arrays.

•	The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

In [ ]:
arr = np.arange(1,13)
arr

In [ ]:
x = np.searchsorted(arr,7)
x

## Search From the Right Side

•	By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [ ]:
arr = np.arange(1,13)
arr


In [ ]:
b = np.sort(arr)
b

In [ ]:
x = np.searchsorted(b,5,side = 'right')
x

In [ ]:
x = np.searchsorted(b,5,side = 'left')
x

## Filtering Arrays
•	Getting some elements out of an existing array and creating a new array out of them is called filtering.

•	In NumPy, you filter an array using a boolean index list.

•	A boolean index list is a list of booleans corresponding to indexes in the array.

•	If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [ ]:
arr = np.array([41,42,43,44])

In [ ]:
x = [True,False,True,False]
newarr = arr[x]
newarr

In [ ]:
arr = np.arange(1,16)

In [ ]:
filter_arr = []

In [ ]:
for i in arr:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
newarr

In [ ]:
filter_arr = arr%2==0
filter_arr

In [ ]:
newarr = arr[filter_arr]
newarr

## Random


# Random Numbers
* Random numbers are numbers that are generated in such a way that each number has an equal probability of being chosen within a specified range.
* Random Numbers are used in a wide range of applications, from scientific simulations to cryptography (including key generation, encryption, digital signatures, and secure communication protocols) and gaming
  
	- Random Events (The locations and times at which enemies appear can be controlled by random numbers to keep gameplay unpredictable and engaging)
	- Randomized Outcomes (Shuffling a deck of cards in digital card games relies on random numbers to ensure fair play and unpredictability).)
* However, not all random numbers are created equal. They can be broadly categorized into two types:
  
 	1. pseudo-random numbers 
 	2. True random numbers
     
## True Random Numbers
True Random Numbers are generated from physical processes that are inherently unpredictable, like radioactive decay or atmospheric noise.

* Unpredictable: Their next value can't be guessed.
* Examples: Flipping a coin, rolling a dice, measuring radioactive decay.
  
## Pseudo-Random Numbers
Pseudo-Random Numbers are generated using algorithms and a starting value called a seed. They appear random, but are actually predictable if you know the seed.

* Deterministic: If you start with the same seed, you get the same sequence of numbers.
* Examples: Random numbers generated by computer algorithms like the Linear Congruential Generator (LCG).

	True Random Numbers: Best for cryptographic applications because they are truly unpredictable.

	Pseudo-Random Numbers: Suitable for non-cryptographic applications where high speed and reproducibility are important.

## Random Number Generation in NumPy
* Python defines a set of functions that are used to generate or manipulate random numbers through the random module. 
* Functions in the random module rely on a pseudo-random number generator function random(), which generates a random float number between 0.0 and 1.0.
* This particular type of functions is used in a lot of games, lotteries, or any application requiring a random number generation.

### Rnadom float

In [327]:
ran = np.random.rand(10)
ran

array([0.02161994, 0.1861005 , 0.45441368, 0.87480107, 0.41216781,
       0.15041397, 0.42459266, 0.106131  , 0.50058572, 0.98704836])

In [368]:
ran = np.random.rand(5,5)
ran

array([[0.86269068, 0.45692619, 0.73962314, 0.06082249, 0.42062674],
       [0.70975903, 0.41663466, 0.39158563, 0.28324389, 0.72692659],
       [0.2969267 , 0.55321308, 0.18733202, 0.57297313, 0.06899244],
       [0.04926199, 0.081456  , 0.21631121, 0.02731226, 0.52584581],
       [0.64450905, 0.86878854, 0.18287608, 0.4414453 , 0.99438424]])

In [376]:
ran = np.random.rand(3,2,4)
ran

array([[[0.98069745, 0.04342282, 0.23804182, 0.74982312],
        [0.68485823, 0.91382642, 0.60296375, 0.46334573]],

       [[0.17788682, 0.7745667 , 0.37788568, 0.31173479],
        [0.11436698, 0.68943777, 0.05847159, 0.04455721]],

       [[0.17312146, 0.22545821, 0.90988829, 0.43135528],
        [0.99918423, 0.56652943, 0.72820967, 0.84176089]]])

### Rnadom Int

In [345]:
ran = np.random.randint(1,10,5)
ran

array([7, 5, 6, 4, 2])

In [353]:
ran = np.random.randint(5)
ran

2

In [357]:
ran = np.random.randint(10,20)
ran

10

In [359]:
ran = np.random.randint(10,20)
ran

11

In [361]:
ran = np.random.randint(10,20,6)
ran

array([11, 14, 16, 12, 15, 12])

In [363]:
ran = np.random.randint(10,100,6)
ran

array([35, 14, 87, 63, 27, 92])

### random.uniform

In [381]:
ran = np.random.uniform(10,15)
ran

11.154719182833496

In [385]:
ran = np.random.uniform(20,25)
ran

21.52450161283247

In [389]:
ran = np.random.uniform(20,30,5)
ran

array([25.33647122, 21.61090906, 24.16724861, 22.39090483, 22.85942408])

In [393]:
ran = np.random.uniform(10,20,10)
ran

array([16.46103088, 14.34944893, 19.79502693, 10.65572866, 10.47071942,
       17.43476602, 10.09757664, 11.67061426, 15.35868182, 19.77193852])

### normal Distribution

In [403]:
ran = np.random.randn(10)
ran

array([-0.24586162,  0.72895689, -0.01655792,  0.42445975,  0.14544833,
        0.21609947,  1.17122242, -0.26742724, -0.60528896, -1.8840935 ])

In [411]:
ran = np.random.randn(2,3,4)
ran

array([[[ 1.51106584e+00,  1.56457663e+00, -6.79588735e-01,
         -1.58032549e+00],
        [ 5.77563778e-01,  1.70260760e+00, -4.20252343e-01,
         -8.06766185e-01],
        [ 2.03203636e+00,  3.45210265e-01,  2.52558138e-01,
          6.80472883e-01]],

       [[-6.94347088e-01,  9.31669338e-01, -2.80015833e-01,
          9.05042870e-02],
        [ 3.17858221e-01,  1.79546590e+00, -6.63090874e-01,
          8.77340302e-01],
        [-1.07679631e-01, -7.13208645e-04, -2.67189946e-01,
         -9.75337110e-01]]])

### Random.Choice
#### without Replace

In [419]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = False)
ran

array([10, 40, 50])

In [423]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = False)
ran

array([20, 10, 50])

In [427]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = False)
ran

array([30, 20, 50])

In [454]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = False)
ran

array([30, 40, 20])

#### With Replace

In [438]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = True)
ran

array([40, 20, 30])

In [440]:
ran = np.random.choice([10,20,30,40,50],size = 3,replace = True)
ran

array([20, 20, 20])

In [448]:
ran = np.random.choice([10,20,30,40,50],size = 4 ,replace = True)
ran

array([40, 50, 30, 10])

In [450]:
ran = np.random.choice([10,20,30,40,50],size = 4,replace = True)
ran

array([50, 10, 50, 30])

In [452]:
ran = np.random.choice([10,20,30,40,50],size = 4,replace = True)
ran

array([20, 30, 40, 30])

### seed

In [457]:
np.random.seed(42)
ran = np.random.randint(10,20,5)
ran

array([16, 13, 17, 14, 16])

### Shuffling

In [466]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [470]:
np.random.shuffle(arr)
arr

array([9, 5, 0, 8, 2, 7, 3, 6, 1, 4])