In [ ]:
import numpy as np

## 0D

In [ ]:
arr = np.array(42)
arr

In [ ]:
arr.ndim

In [ ]:
type(arr)

## 1D

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
arr.ndim

In [ ]:
type(arr)

In [ ]:
arr.shape

In [ ]:
arr.size

## 2D

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

## 3D

In [ ]:
arr = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
])
arr

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

## Access
### 1D

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
arr[0]

In [ ]:
arr[2]

### 2D

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
arr[1,1]

In [ ]:
arr[0,2]

### 3D

In [ ]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
arr

In [ ]:
arr[0,1,1]

In [ ]:
arr[1,0,2]

In [ ]:
arr[1,0,-1]

## Slicing
### 1D

In [ ]:
arr = np.array([1,2,3,4,5])
arr

In [ ]:
arr[1:4]

In [ ]:
arr[0:5]

In [ ]:
arr[0:4]

### 2D

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

In [ ]:
arr[1,:]

In [ ]:
arr[1,1:]

In [ ]:
arr[0,1:4]

### 3D

In [ ]:
arr = np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[11,12,13,14,15],[16,17,18,19,20]]
])
arr

In [ ]:
arr[0,1,1:4]

In [ ]:
arr[1,:]

In [ ]:
arr[0,1,:]

## Step

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

In [ ]:
arr[1:10:4]

In [ ]:
arr[1:10:2]

In [ ]:
arr[1:10:3]

## Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
type(arr)

In [ ]:
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4],dtype = 'i')
arr.dtype

In [ ]:
arr

In [ ]:
arr = np.array([1,2,3,4],dtype = 'f')
arr

In [ ]:
arr.dtype

## Converting Data Type on Existing Arrays

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
newarr = arr.astype('f')
newarr

In [ ]:
newarr1 = newarr.astype('S')
newarr1

In [ ]:
newarr2 = newarr.astype('i')
newarr2

## Copy

In [ ]:
arr1 = np.array([1,2,3,4])
arr1

In [ ]:
df1 = arr1.copy()

In [ ]:
arr1[0] = 42
arr1

In [ ]:
df

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

In [ ]:
df = arr.copy()
df

In [ ]:
df[0,1] = 10
arr[0,1] = 20

In [ ]:
print(arr)
print(df)

## View

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
df = arr.view()
df

In [ ]:
arr[0] = 15

In [ ]:
print(arr)
print(df)

In [ ]:
df[2] = 30

In [ ]:
print(arr)
print(df)

## Check View And Copy

In [ ]:
print(df1.base)

In [ ]:
print(df.base)

## Reshape

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
newarr = arr.reshape(2,5)
newarr

In [ ]:
arr = np.arange(1,16)
arr

In [ ]:
newarr = arr.reshape(3,5)
newarr

In [ ]:
arr = np.arange(1,13)
arr

In [ ]:
newarr = arr.reshape(2,6)
newarr

In [ ]:
newarr = arr.reshape(2,2,3)
newarr

In [ ]:
x = newarr.reshape(-1)
x

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
newarr = arr.reshape(-1)
newarr

## Other functions that commonly used for array creation

## 1. Areange()

In [ ]:
arr = np.arange(0,11,2)
arr

## 2. ones()

In [ ]:
arr = np.ones((3,4),dtype = 'i')
arr

In [ ]:
arr = np.ones((3,3,4),dtype = 'i')
arr

## 3.zeros()

In [ ]:
arr = np.zeros((3,4),dtype = 'i')
arr

In [ ]:
arr = np.zeros((3,3,4),dtype = 'i')
arr

## 4.linspace()

In [ ]:
arr = np.linspace(0,1,5)
arr

In [ ]:
arr = np.linspace(0,10,5)
arr

## 5.Diag()

In [ ]:
arr = np.diag([1,2,3,4,5])
arr

In [ ]:
arr =  np.diag([4,5,6,7,8])
arr

## 6. eye()

In [ ]:
arr = np.eye(4)
arr

In [ ]:
arr = np.eye(10)
arr

## Mathematical Operations

## 1. Add

In [ ]:
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])

In [ ]:
a = np.add(arr,arr1)
a

## 2. subtract

In [ ]:
b = np.subtract(arr1,arr)
b

In [ ]:
b = np.subtract(arr,arr1)
b

## 3. multiply

In [ ]:
c = np.multiply(arr,arr1)
c

## 4. Dot

In [ ]:
d = np.dot(arr,arr1)

In [ ]:
d

## 5.sum()

In [ ]:
a = np.sum(arr)

In [ ]:
a

## mean()

In [ ]:
a = np.mean(arr)

In [ ]:
a

## Standard deviation 

In [ ]:
a = np.std(arr)

In [ ]:
a

## min

In [ ]:
a = np.min(arr)

In [ ]:
a

## max

In [ ]:
a = np.max(arr)

In [ ]:
a

## variance

In [ ]:
a = np.var(arr)

In [ ]:
a

## Iterating Arrays

## nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
for x in np.nditer(arr):
    print(x)

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
for x in np.nditer(arr):
    print(x)

## ndenumerate()

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
for x in np.ndenumerate(arr):
    print(x)

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
for x in np.ndenumerate(arr):
    print(x)

## Joining NumPy Arrays
## Concatenate()

In [ ]:
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])

In [ ]:
a = np.concatenate((arr,arr1))

In [ ]:
a

In [ ]:
arr1 = np.array([[2, 5,9], [4,1,3]])
arr2 = np.array([[5,8,3], [4,6, 1]])


In [ ]:
a = np.concatenate((arr1,arr2))
a

In [ ]:
a = np.concatenate((arr1,arr2),axis = 1)
a

## Stack()

In [202]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [206]:
arr = np.stack((arr1,arr2))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [208]:
arr = np.stack((arr1,arr2),axis = 1)
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## hstack

In [211]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [213]:
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [217]:
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

## vstack

In [220]:
array1 = np.array([ [[1, 2, 3]], [[4, 5, 6]] ])
array2 = np.array([[[7, 8, 9]], [[10, 11, 12]]])

In [224]:
arr = np.vstack((array1,array2))
arr

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

## dstack

In [229]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])


In [233]:
arr = np.dstack((array1,array2))
arr

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [239]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])


In [241]:
arr = np.dstack((array1,array2))
arr

array([[[ 1,  2,  9, 10],
        [ 3,  4, 11, 12]],

       [[ 5,  6, 13, 14],
        [ 7,  8, 15, 16]]])

## Split()

In [244]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [248]:
arr1 = np.array_split(arr,2)
arr1

[array([1, 2, 3]), array([4, 5, 6])]

In [250]:
arr1 = np.array_split(arr,3)
arr1

[array([1, 2]), array([3, 4]), array([5, 6])]

In [254]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [260]:
arr1 = np.array_split(arr,2,axis = 1)
arr1

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]